/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Apache.Hive.Service.Rpc.Thrift
{
  public enum TJobExecutionStatus
  {
    IN_PROGRESS = 0,
    COMPLETE = 1,
    NOT_AVAILABLE = 2,
  }
}
