/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Apache.Hive.Service.Rpc.Thrift
{

  public partial class TOpenSessionResp : TBase
  {
    private TSessionHandle _sessionHandle;
    private Dictionary<string, string> _configuration;

    public TStatus Status { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="TProtocolVersion"/>
    /// </summary>
    public TProtocolVersion ServerProtocolVersion { get; set; }

    public TSessionHandle SessionHandle
    {
      get
      {
        return _sessionHandle;
      }
      set
      {
        __isset.sessionHandle = true;
        this._sessionHandle = value;
      }
    }

    public Dictionary<string, string> Configuration
    {
      get
      {
        return _configuration;
      }
      set
      {
        __isset.configuration = true;
        this._configuration = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool sessionHandle;
      public bool configuration;
    }

    public TOpenSessionResp()
    {
      this.ServerProtocolVersion = TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V10;
    }

    public TOpenSessionResp(TStatus status, TProtocolVersion serverProtocolVersion) : this()
    {
      this.Status = status;
      this.ServerProtocolVersion = serverProtocolVersion;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_status = false;
        bool isset_serverProtocolVersion = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                Status = new TStatus();
                await Status.ReadAsync(iprot, cancellationToken);
                isset_status = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                ServerProtocolVersion = (TProtocolVersion)await iprot.ReadI32Async(cancellationToken);
                isset_serverProtocolVersion = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Struct)
              {
                SessionHandle = new TSessionHandle();
                await SessionHandle.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Map)
              {
                {
                  Configuration = new Dictionary<string, string>();
                  TMap _map76 = await iprot.ReadMapBeginAsync(cancellationToken);
                  for(int _i77 = 0; _i77 < _map76.Count; ++_i77)
                  {
                    string _key78;
                    string _val79;
                    _key78 = await iprot.ReadStringAsync(cancellationToken);
                    _val79 = await iprot.ReadStringAsync(cancellationToken);
                    Configuration[_key78] = _val79;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_status)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_serverProtocolVersion)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TOpenSessionResp");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "status";
        field.Type = TType.Struct;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Status.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "serverProtocolVersion";
        field.Type = TType.I32;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)ServerProtocolVersion, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if (SessionHandle != null && __isset.sessionHandle)
        {
          field.Name = "sessionHandle";
          field.Type = TType.Struct;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await SessionHandle.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Configuration != null && __isset.configuration)
        {
          field.Name = "configuration";
          field.Type = TType.Map;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.String, Configuration.Count), cancellationToken);
            foreach (string _iter80 in Configuration.Keys)
            {
              await oprot.WriteStringAsync(_iter80, cancellationToken);
              await oprot.WriteStringAsync(Configuration[_iter80], cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TOpenSessionResp(");
      sb.Append(", Status: ");
      sb.Append(Status== null ? "<null>" : Status.ToString());
      sb.Append(", ServerProtocolVersion: ");
      sb.Append(ServerProtocolVersion);
      if (SessionHandle != null && __isset.sessionHandle)
      {
        sb.Append(", SessionHandle: ");
        sb.Append(SessionHandle== null ? "<null>" : SessionHandle.ToString());
      }
      if (Configuration != null && __isset.configuration)
      {
        sb.Append(", Configuration: ");
        sb.Append(Configuration);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
