/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Apache.Hive.Service.Rpc.Thrift
{

  public partial class TTypeQualifiers : TBase
  {

    public Dictionary<string, TTypeQualifierValue> Qualifiers { get; set; }

    public TTypeQualifiers()
    {
    }

    public TTypeQualifiers(Dictionary<string, TTypeQualifierValue> qualifiers) : this()
    {
      this.Qualifiers = qualifiers;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_qualifiers = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map)
              {
                {
                  Qualifiers = new Dictionary<string, TTypeQualifierValue>();
                  TMap _map0 = await iprot.ReadMapBeginAsync(cancellationToken);
                  for(int _i1 = 0; _i1 < _map0.Count; ++_i1)
                  {
                    string _key2;
                    TTypeQualifierValue _val3;
                    _key2 = await iprot.ReadStringAsync(cancellationToken);
                    _val3 = new TTypeQualifierValue();
                    await _val3.ReadAsync(iprot, cancellationToken);
                    Qualifiers[_key2] = _val3;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_qualifiers = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_qualifiers)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TTypeQualifiers");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "qualifiers";
        field.Type = TType.Map;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Qualifiers.Count), cancellationToken);
          foreach (string _iter4 in Qualifiers.Keys)
          {
            await oprot.WriteStringAsync(_iter4, cancellationToken);
            await Qualifiers[_iter4].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TTypeQualifiers(");
      sb.Append(", Qualifiers: ");
      sb.Append(Qualifiers);
      sb.Append(")");
      return sb.ToString();
    }
  }

}
